config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static#home'

  get '/about', to: 'static#about'

  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :project_languages
  has_many :projects, through: :project_languages
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_languages
  has_many :languages, through: :project_languages
end

app/models/project_language.rb
class ProjectLanguage < ApplicationRecord
  belongs_to :project
  belongs_to :language
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable,
    :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index, :show]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(
        :title,
        :subtitle,
        :live_link,
        :walkthroughId,
        :code_sessionId,
        :image,
        :extra_image,
        :description_1,
        :description_2
      )
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:home, :about]

  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Z Code Doc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid' style="overflow: hidden">
      <div class='row'>
        <div class='col-sm-1 logo'>
          <div id='logo'>
            <%= image_tag('logo.jpg', alt: 'logo') %>
          </div>
        </div>
        <div class='col-sm-9'>
          <%= yield %>
        </div>
        <div class='col-sm-2 sidebar'>
          <% if user_signed_in? %>
             <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          <% end %>
          <h3>Welcome</h3>
          <%= link_to 'Home', '/' %>
          <%= link_to 'Z Doc', '/about' %>
          <%= link_to 'Projects', '/projects' %>
          <%= link_to 'Videos',
            'https://www.youtube.com/playlist?list=PLrYWLylYK_la-Lgbdy3C-SH7FV1HBXPs4',
            target: '_blank'
          %>
          <%= link_to 'Blog', 'https://nickisknowledge.github.io/.', target: '_blank' %>
          <hr />
          <h3 class='description'>Narrative</h3>
          <p class='p1'>Persistent</p>
          <p class='p2'>Innovative</p>
          <p class='p3'>Lively</p>
          <p class='p4'>Practical</p>
          <p class='p5'>Ambitious</p>
          <p class='p2'>Flexible</p>
          <p class='p3'>Proactive</p>
          <p class='p4'>Unique</p>
          <p class='p5'>Trouble -</p>
          <p class='p2'>Shooter</p>
          <p class='p3'>Team player</p>
          <p class='p4'>Meticulous</p>
          <p class='p5'>Resourceful</p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title, class: 'title_input' %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :project_subtitle, class: 'title_input' %>
  </div>

  <div class="field">
    <%= form.label :live_link %>
    <%= form.text_field :live_link, id: :project_live_link, class: 'link_input' %>
  </div>

  <div class="field">
    <%= form.label :walkthroughId %>
    <%= form.text_field :walkthroughId, id: :project_walkthroughId, class: 'link_input' %>
  </div>
  <div class="field">
    <%= form.label :code_sessionId %>
    <%= form.text_field :code_sessionId, id: :project_code_sessionId, class: 'link_input' %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :project_image, class: 'image_input' %>
  </div>

  <div class="field">
    <%= form.label :extra_image %>
    <%= form.text_field :extra_image, id: :project_extra_image, class: 'image_input' %>
  </div>

  <div class="field">
    <%= form.label :description_1, class: 'description_label' %>
    <%= form.text_area :description_1, id: :project_description_1, class: 'description_input' %>
  </div>

  <div class="field">
    <%= form.label :description_2, class: 'description_label' %>
    <%= form.text_area :description_2, id: :project_description_2, class: 'description_input' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project_language.html.erb
<% if (project.languages.count > 1) %>
  <div class='lang_logo_container'>
    <% project.languages.each do |lang| %>
        <%= image_tag("logos/#{lang.image}",
          alt: lang.title,
          class: 'lang_logos')
        %>
    <% end %>
  </div>
<% else %>
<%= image_tag("logos/#{project.languages.first.image}",
    alt: "#{project.languages.first.title}_logo",
    class: 'lang_logo')
  %>
<% end %>

app/views/projects/edit.html.erb
<div style='background: black'>
  <h1>Editing Project</h1>

  <%= render 'form', project: @project %>

  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %>

</div>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
    <div class='row'>
      <div class='col-sm'>
        <%= link_to image_tag(project.image, alt: project.title, size: '350x350'),
        project_path(project) %>
      </div>
      <div class='col-sm'>
        <h1 class='index_title'><%= project.title %></h1>
        <%= render 'project_language', project: project %>
      </div>
    </div>
    <hr class='index_divider'/>
<% end %>

app/views/projects/new.html.erb
<div class='wrapper' style='background: black'>
  <h1>New Project</h1>

  <%= render 'form', project: @project %>

  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class='show_page'>
  <div class="center">
    <h1><%=  @project.title %></h1>
    <h5><%= @project.subtitle %></h5>
  </div>

  <div class="row">
    <div class="col-sm-7">
      <h3>Description</h3>
      <div class='descrip_1'>
        <%= @project.description_1 %>
      </div>
      <div class='descrip_2'>
        <%= @project.description_2 %>
      </div>
      <div  class='live_link'>
        <% if @project.title.include?('Gem') %>
          Link to <%= link_to 'Gem', @project.live_link, target: '_blank' %>!
        <% elsif @project.live_link.include?('github') %>
          Link to <%= link_to 'Githib', @project.live_link, target: '_blank' %>!
        <% else %>
          Live <%= link_to 'link', @project.live_link, target: '_blank' %>!
        <% end %>
      </div>
    </div>

    <div class="col-sm-5">
      <div class="photos">
        <%= image_tag(@project.image , alt: @project.title,
        class: 'prj_main_img') %>
      </div>
    </div>
  </div>

  <div class='row iframe'>
    <div class="col-sm-12">
      Walkthrough video: (click me!)
      <br />
      <div class="youtube-player" data-id="<%= @project.walkthroughId %>"></div>
    </div>
  </div>

  <div class='row'>
    <% if (@project.code_sessionId.present?) %>
      <div class='col-sm-12'>
        Coding Session video: (click me!)
        <br />
        <div class="youtube-player" data-id="<%= @project.code_sessionId %>"></div>
      </div>
    <% end %>
  </div>

  <div style="text-align: center">
    <% if (@project.extra_image.present?) %>
      <div class='row extra_image'>
        <div class='col-sm-12'>
          <%= image_tag("extra_images/#{@project.extra_image}",
            alt: @project.extra_image)
          %>
        </div>
      </div>
    <% end %>
  </div>
</div>